version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-t1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus-network

networks:
  prometheus-network:
    driver: bridge