global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

rule_files:
#  - "alert.rules.yml"
#  - "rules.yml"

scrape_configs:
  - job_name: "z-product-service"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["lenovopc-local:9081"]
  - job_name: "z-order-service"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["lenovopc-local:8082"]
  - job_name: "z-inventory-service"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["lenovopc-local:8083"]
  - job_name: "gateway-service"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["lenovopc-local:8080"]
