version: '3.8'
services:
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - ./docker-compose-data/keycloak/db/:/var/keycloak/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      - api-gateway-service-network
  keycloak-app:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.0
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker-compose-data/keycloak/realm/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
    networks:
      - api-gateway-service-network

  java_app_gateway:
    image: img/api-gateway-service-1-0-0-staged
    ports:
      - "8080:8080"
    restart: always
    networks:
      - api-gateway-service-network

networks:
  api-gateway-service-network:
