version: '3.9'

services:
  postgres-master:
    image: postgres:latest
    container_name: postgres-master
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-z-inventory-service
    volumes:
      - ./data/master:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-cluster

  postgres-slave:
    image: postgres:latest
    container_name: postgres-slave
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-z-order-inventory-slave
      POSTGRES_MASTER_SERVICE_HOST: postgres-master
      POSTGRES_MASTER_SERVICE_PORT: 6432
    volumes:
      - ./data/slave:/var/lib/postgresql/data
    networks:
      - postgres-cluster

networks:
  postgres-cluster:
    driver: bridge
